*** Starting uWSGI 2.0.21 (64bit) on [Wed Jan 18 18:16:24 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 11 January 2023 05:09:41
os: Linux-3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/web/Desktop/predictProject/predictProject
detected binary path: /home/web/python/bin/uwsgi
chdir() to /home/web/Desktop/predictProject
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 6
Python version: 3.9.13 (main, Jan 10 2023, 21:03:27)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x1c2a970
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507960 bytes (496 KB) for 4 cores
*** Operational MODE: preforking ***
spawned uWSGI master process (pid: 60321)
spawned uWSGI worker 1 (pid: 60325, cores: 1)
spawned uWSGI worker 2 (pid: 60326, cores: 1)
spawned uWSGI worker 3 (pid: 60327, cores: 1)
spawned uWSGI worker 4 (pid: 60328, cores: 1)
Python auto-reloader enabled
Traceback (most recent call last):
  File "/home/web/Desktop/predictProject/./predictProject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/web/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/web/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/web/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/web/Desktop/predictProject/./predictProject/settings.py", line 122, in <module>
    STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
NameError: name 'os' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/home/web/Desktop/predictProject/./predictProject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/web/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/web/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/web/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/web/Desktop/predictProject/./predictProject/settings.py", line 122, in <module>
    STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
NameError: name 'os' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/home/web/Desktop/predictProject/./predictProject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/web/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/web/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/web/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/web/Desktop/predictProject/./predictProject/settings.py", line 122, in <module>
    STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
NameError: name 'os' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/home/web/Desktop/predictProject/./predictProject/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/web/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/web/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/web/python/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/web/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/web/Desktop/predictProject/./predictProject/settings.py", line 122, in <module>
    STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
NameError: name 'os' is not defined
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uwsgi_proto_uwsgi_parser(): Success [proto/uwsgi.c line 40]
*** Starting uWSGI 2.0.21 (64bit) on [Thu Jan 19 00:54:09 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 11 January 2023 05:09:41
os: Linux-3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/web/Desktop/predictProject/predictProject
detected binary path: /home/web/python/bin/uwsgi
chdir() to /home/web/Desktop/predictProject
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 6
Python version: 3.9.13 (main, Jan 10 2023, 21:03:27)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0xede950
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507960 bytes (496 KB) for 4 cores
*** Operational MODE: preforking ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 67344)
spawned uWSGI worker 1 (pid: 67350, cores: 1)
spawned uWSGI worker 2 (pid: 67351, cores: 1)
spawned uWSGI worker 3 (pid: 67352, cores: 1)
spawned uWSGI worker 4 (pid: 67353, cores: 1)
Python auto-reloader enabled
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xede950 pid: 67353 (default app)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xede950 pid: 67351 (default app)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xede950 pid: 67352 (default app)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xede950 pid: 67350 (default app)
*** Starting uWSGI 2.0.21 (64bit) on [Thu Jan 19 01:04:49 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 11 January 2023 05:09:41
os: Linux-3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/web/Desktop/predictProject/predictProject
detected binary path: /home/web/python/bin/uwsgi
chdir() to /home/web/Desktop/predictProject
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 6
Python version: 3.9.13 (main, Jan 10 2023, 21:03:27)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x20a6980
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 507960 bytes (496 KB) for 4 cores
*** Operational MODE: preforking ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 67756)
spawned uWSGI worker 1 (pid: 67763, cores: 1)
spawned uWSGI worker 2 (pid: 67764, cores: 1)
spawned uWSGI worker 3 (pid: 67765, cores: 1)
spawned uWSGI worker 4 (pid: 67766, cores: 1)
Python auto-reloader enabled
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20a6980 pid: 67764 (default app)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20a6980 pid: 67763 (default app)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20a6980 pid: 67766 (default app)
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20a6980 pid: 67765 (default app)
uwsgi_proto_uwsgi_parser(): Inappropriate ioctl for device [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
*** Starting uWSGI 2.0.21 (64bit) on [Thu Jan 19 01:37:24 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 11 January 2023 05:09:41
os: Linux-3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/web/Desktop/predictProject/predictProject
detected binary path: /home/web/python/bin/uwsgi
chdir() to /home/web/Desktop/predictProject
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000/submit).
bind(): Address already in use [core/socket.c line 769]
uwsgi_proto_uwsgi_parser(): Inappropriate ioctl for device [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
*** Starting uWSGI 2.0.21 (64bit) on [Thu Jan 19 16:19:55 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 11 January 2023 05:09:41
os: Linux-3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/web/Desktop/predictProject/predictProject
detected binary path: /home/web/python/bin/uwsgi
chdir() to /home/web/Desktop/predictProject
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
uwsgi_proto_uwsgi_parser(): Resource temporarily unavailable [proto/uwsgi.c line 40]
[uwsgi-python-reloader] module/file /home/web/Desktop/predictProject/./predictProject/settings.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 67763)...
Gracefully killing worker 3 (pid: 67765)...
Gracefully killing worker 2 (pid: 67764)...
Gracefully killing worker 4 (pid: 67766)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/web/Desktop/predictProject/predictProject
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 6 mapped to socket 0 (127.0.0.1:8000)
running /home/web/python/bin/uwsgi
[uWSGI] getting INI configuration from predictProject.ini
*** Starting uWSGI 2.0.21 (64bit) on [Wed Jan 25 01:31:36 2023] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 11 January 2023 05:09:41
os: Linux-3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/web/Desktop/predictProject/predictProject
detected binary path: /home/web/python/bin/uwsgi
your processes number limit is 4096
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 1024
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8080 fd 3
Python version: 3.9.13 (main, Jan 10 2023, 21:03:27)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xea6770
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 296472 bytes (289 KB) for 2 cores
*** Operational MODE: preforking ***
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 67756)
spawned uWSGI worker 1 (pid: 95808, cores: 1)
spawned uWSGI worker 2 (pid: 95809, cores: 1)
